### ISSUE TITLE
Add support to use local Ollama eller llamacpp models

### ISSUE THREAD

**Issue by mcotdev** [pretzelai/pretzelai#114]
Would like to see support to use local LLM models, using either Ollama or llama.cpp

**Comment by captainpete** [comment]
Note: For Ollama support, see #117

**Comment by prasoon2211** [comment]
Hi @mcotdev - we added Ollama and other model support (Anthropic, Groq, Mistral) in the v4.2.8 release!
https://github.com/pretzelai/pretzelai/releases/tag/v4.2.8

See the [configuration](https://github.com/pretzelai/pretzelai?tab=readme-ov-file#configuration) section in README to see how to enable Ollama.

See this image of me selecting a Ollama model:
![image](https://github.com/user-attachments/assets/6f73c5ba-8c26-4b92-b231-4b90d6d9e256)

**Comment by prasoon2211** [comment]
I will add a caveat - if you use a small model (i.e. anything under 33b series of models), you'll might not get amazing outputs because right now, the prompt is pretty complex and only bigger models can handle the complex prompt. 

We're working on having easier-to-follow prompts for smaller models.
