### ISSUE TITLE
Add archive with static assets to releases

### ISSUE THREAD

**Issue by AlphaJack** [pretzelai/pretzelai#31]
Hi, can we have a zip archive with the static assets already build, as [Cyberchef](https://github.com/gchq/CyberChef/releases/) does for every release?

**Comment by prasoon2211** [comment]
Sounds good, we'll develop a release process soon. Until that happens, https://pretzel.github.io closely track main and you can find the zip ready to be deployed here:
https://github.com/pretzelai/pretzelai.github.io/archive/refs/heads/main.zip

Because of CORS issues with PRQL, simply opening the `index.html` on your local machine doesn't work yet - we're looking into fix this soon.

Create an issue here for the release process: https://github.com/pretzelai/pretzelai/issues/37

**Comment by ramonverse** [comment]
Issue duplicated by newer https://github.com/pretzelai/pretzelai/issues/37
